### ISSUE TITLE
energy repair not working with mekanism

### ISSUE THREAD

**Issue by tyler489** [Bartz24/MoarTinkers#11]
mekanism uses joules it seems it doesnt work with energy repair... or maybe i dont understand how it works

**Comment by Bartz24** [comment]
the items repair right after you use the item, and from items in your inventory (like flux capacitors)

**Comment by tyler489** [comment]
yes but it wont draw power from mekanism energy tablets... also it wont draw from anything from slots from 1-9 only inventory

**Comment by Bartz24** [comment]
alright ill look into it

**Comment by tyler489** [comment]
also noticed that it wont find energy sources in your hotbar.

**Comment by Bartz24** [comment]
Appears to be working in the new 0.6.0
