### ISSUE TITLE
[1.12.1][0.5.4] Could not determine owner

### ISSUE THREAD

**Issue by Kris1432** [Bartz24/MoarTinkers#12]
![image](https://user-images.githubusercontent.com/3301022/29402463-ed06d14c-832c-11e7-9a66-0b6886e3403d.png)

I'm sure you know about this already, but my players are getting this when trying to log into the server, I'm aware its a forge bug, but even after removing your mod, people are still getting this error.

Forge: 2456

**Comment by tyler489** [comment]
If the mod is removed from the server try removing it from clients. Also i was told that if u join a sp world then a mp world you wont get that error

**Comment by Kris1432** [comment]
yeah, the clients have removed it too, but interesting, I will see if that works.

**Comment by Bartz24** [comment]
it's a forge issue that's been happening on 1.12 recently....sorry
