### ISSUE TITLE
[1.12] No materials from ProjectE

### ISSUE THREAD

**Issue by peregrinus11** [Bartz24/MoarTinkers#13]
There seems to be a problem with ProjectE materials (Dark/Red Matter) - they are not recognized as valid materials for parts (they do not occur in the "Materials and You" book)

**Comment by Staegrin** [comment]
The log when you start Minecraft says 

"Unable to parse dependency for mod 'moartinkers' with dependency string 'after:EnderIO'. The modId 'EnderIO' must be all lowercase.
--
11:21:18 | FML | main | Unable to parse dependency for mod 'moartinkers' with dependency string 'after:ProjectE'. The modId 'ProjectE' must be all lowercase."

So they need to change their code to lower case letters and check vs the 1.12 version of ProjectE

**Comment by Bartz24** [comment]
Fixed in 0.6.0
