### ISSUE TITLE
Vibrant Alloy "Ender Magnetic" not working with ranged weapons.

### ISSUE THREAD

**Issue by NiSiSuinegEht** [Bartz24/MoarTinkers#14]
Version 0.4.1 for Minecraft 1.10.2

Neither on the bow, nor the arrows, will the Ender Magnetic trait collect items.  Even using the bow as a melee weapon won't do it.  I have confirmed it working on a broadsword, however.

I've not tried other versions of Moar Tinkers, as this is the latest for 1.10.2, and the modpack I am using (The Simple Life 2) hasn't been rebuilt for later versions of Minecraft.

**Comment by Bartz24** [comment]
Vibrant Alloy material removed in 0.6.0.
May look at later
