### ISSUE TITLE
Don't add if mod isn't present

### ISSUE THREAD

**Issue by Jomik** [Bartz24/MoarTinkers#15]
I'd suggest not adding things for a mod, if the mod isn't present, as it clutters JEI and the book quite a bit.

**Comment by Bartz24** [comment]
I would do this but imagine this:
Some mods have common materials like invar, platinum, maybe constantan, etc
If I disable some based on what mods there are....some might not pop up. 
Meaning a config option would be required to force it to load
But there's already a config file to disable the ones you don't want, so not happening...the modding world to have it automatically work around, so just use the config options
