### ISSUE TITLE
Base Metals Conflict

### ISSUE THREAD

**Issue by Keetarin** [Bartz24/MoarTinkers#17]
Hi, Base Metals has added tcon integration. could you look into it as there seems to be a conflict.

**Comment by jusitnboggs** [comment]
I 2nd this also here is my log
[crash-2017-12-18_07.57.20-client.txt](https://github.com/Bartz24/MoarTinkers/files/1568634/crash-2017-12-18_07.57.20-client.txt)
`

**Comment by Bartz24** [comment]
Moar Tinkers will now check for materials loaded already, and if one is detected it won't add one.

This may still cause conflicts with other mods though, but compat with Base Metals should be fine in the new version coming soon
