### ISSUE TITLE
Unable to make Invar Bolts

### ISSUE THREAD

**Issue by lightlike** [Bartz24/MoarTinkers#18]
Minecraft Version: 1.12.2
Forge: 14.23.1.2564
More Tinkers: 0.5.4

Unable to pour Invar over arrow shaft to make bolt head (also tried toolrod).
Works fine with Lead or Obsidian. Have not tried any other materials.

**Comment by Bartz24** [comment]
Works in the new 0.6.0 (may have worked early).
You pour the molten metal over an arrow shaft, not tool rod
