### ISSUE TITLE
Certus Quartz Parts don't show up

### ISSUE THREAD

**Issue by tyra314** [Bartz24/MoarTinkers#19]
I've added AE2 and the certus quartz parts aren't added.

> B:"Allow Certus Quartz Material"=true

I'm using:
- Minecraft 1.12.2
- Forge 14.23.1.2568
- MoarTinkers 0.5.4
- TiC 1.12-2.8.1.49
- AE2-rv5-stable-3

Here is the log of the start of the pack: https://gist.github.com/tyra314/186bf40ef4b3ac4d63d67ea1cda73e20

**Comment by Bartz24** [comment]
Fixed in 0.6.0
