### ISSUE TITLE
trait depthdigger

### ISSUE THREAD

**Issue by Staegrin** [Bartz24/MoarTinkers#2]
![2017-03-28_17 17 34](https://cloud.githubusercontent.com/assets/8494635/24413025/7bcb66da-13da-11e7-93be-241af9c0c7fe.png)
Trait for refined obsidian not showing right

**Comment by Bartz24** [comment]
I know :D It was an unused vanilla tinkers trait. It'll be replaced

**Comment by Bartz24** [comment]
Replaced in next version
