### ISSUE TITLE
[1.12.2] [Request] making Yellorium meltable in the smeltery

### ISSUE THREAD

**Issue by Sanofus** [Bartz24/MoarTinkers#20]
The Yelllorium ore of Extreme Reactors cannot be smelted. There is no molten liquid of yellorium added. You have to make it in the pattern station. I think that is a bit weird because it is a metal.

**Comment by JonasCiss** [comment]
To make party of Yellorium you have to use the part builder of TiC. That seems odd. It should be used casts for this.

**Comment by Bartz24** [comment]
Changed in 0.6.0
