### ISSUE TITLE
Moar Tinkers crashing the game the game on startup

### ISSUE THREAD

**Issue by Minecrafter10129** [Bartz24/MoarTinkers#22]
(I do not know how I should format this issue "report")- It keeps crashing the game on startup and it is not in conflict with any other tinkers mods, or any mod that could be adding something that moar tinkers is adding 

--This is the crash report--
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Moar Tinkers (moartinkers)

(I have no idea what any of this stuff means, other than that there is a problem and it causes game failure)

**Comment by YaibaToKen** [comment]
You should post the full log, preferably using [gist](https://gist.github.com/) or [pastebin](https://pastebin.com/) :)
Posting your mod list, complete with versions used as well as the forge version it is crashing with, will also help.
