### ISSUE TITLE
Caught exception from Moar Tinkers --> Material already registered

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [Bartz24/MoarTinkers#26]
Minecraft Version: 1.12.2
MoarTinkers Version: 0.5.4
Enderio Version: 5.0.241-nightly

[crashlog](https://gist.github.com/5t0rmr1d3r/8ef015aa07b8a9d46757415bbb766618)

**Comment by Bartz24** [comment]
Fixed in 0.6.0
