### ISSUE TITLE
EnderIO crash 1.12

### ISSUE THREAD

**Issue by Staegrin** [Bartz24/MoarTinkers#27]
Crash on startup

Intalled:
JEI
Ender IO
Tinker's construct
MoarTinkers

Crashlog
client:
https://gist.github.com/Staegrin/7471c602f8dabb99df5ab72fa7c25bf5
latest:
https://gist.github.com/Staegrin/0a7b3248dd1f39fceb12da370b73a839

**Comment by erwin1234777** [comment]
Got the same issue, seems to be a major one, just dropping a comment to make note this is a big deal and needs to be fixed asap if possible.

**Comment by vinyl90** [comment]
Got the same issue.

**Comment by bdudek** [comment]
disabling the enderio metals in the moartinkers config seems to make it work as tinkers look like it has ender io support itself

**Comment by tyler489** [comment]
@Bartz24 Hey can you disable your integration by default.

**Comment by CreeperBossVJ** [comment]
Hey, @Bartz24, Is there going to be an update to fix this soon. If not I understand, Keep up the good work!

**Comment by Staegrin** [comment]
You need to go into the config and dissable all the enderio metals. Then there will be no more conflicts. Enderio adds it's own tinkers' integration.

**Comment by CreeperBossVJ** [comment]
@Bartz24 Thanks man!

**Comment by BrainStone** [comment]
I agree with @tyler489, that it would be best to disable the EnderIO integration on 1.12, as EnderIO adds it themselves, or to rework it if you want to add traits EnderIO doesn't etc.

**Comment by Bartz24** [comment]
Fixed in 0.6.0
