### ISSUE TITLE
Gaia Spirit Deselecting

### ISSUE THREAD

**Issue by Arkimu** [Bartz24/MoarTinkers#28]
I've seem a problem with all the Gaia Spirit Tools/Weapon, when I select one in the quickbar it keeps showing the message of the weapon I have equip non stop. Like if was deselecting and selecting it self.

![2018-04-08_16 44 59](https://user-images.githubusercontent.com/38189681/38472643-ca1c8f6e-3b50-11e8-8e99-2c85b184e56c.png)

**Comment by Bartz24** [comment]
That is normal. The alien trait causes this. Check the stats of the tool, they'll change.
