### ISSUE TITLE
[Enhancement] Add support for Construct's Armory (Tinker Addon for Armors)

### ISSUE THREAD

**Issue by YaibaToKen** [Bartz24/MoarTinkers#29]

**Comment by YaibaToKen** [comment]
@Bartz24 any info on this?

**Comment by Dragnier** [comment]
Would really love to see this happen.

**Comment by YaibaToKen** [comment]
@Dragnier I have good news and bad news. Unfortunately Bartz no longer has time to maintain the mod. The good news is, I've taken up his mantle.
