### ISSUE TITLE
Config file and compatibility with PlusTic 

### ISSUE THREAD

**Issue by vrork** [Bartz24/MoarTinkers#3]
Hello there. I saw that your mod doenst have a config file so we can disable "modules" we dont need/want. Also, i have to ask, what about compatibility with PlusTic, since both your mods have things in comom that you guys add/change

**Comment by Bartz24** [comment]
Config will be coming soon. Wanted to get everything working first

No PlusTic compatability.

**Comment by vrork** [comment]
As long as we get the config file, we get compatibility i think, because we can enable/disable on your mod things that are also on the other mod

**Comment by aionys** [comment]
I don't care about PlusTiC compatibility, but I would like the ability to edit the configs. I don't like having to have pyrotheum to alloy enderium for example when it's not part of the blend crafting recipe.

**Comment by Bartz24** [comment]
Config file added for next version
