### ISSUE TITLE
Registering issues?

### ISSUE THREAD

**Issue by Yariazen** [Bartz24/MoarTinkers#32]
I don't have any of the draconic evolution stuff and I do have it installed.
I have terrasteel from botania when botania is definately not installed
Same with the extreme reactor stuff and PSI metal.
It seems to have only registered the things that I don't have.
[modList.txt](https://github.com/Bartz24/MoarTinkers/files/2011557/Untitled.txt)

**Comment by Yariazen** [comment]
forge-14.23.3.2698
moartinkers-0.5.4

**Comment by Bartz24** [comment]
All materials appear in 0.6.0, but hopefully I can hide ones not being used soon
