### ISSUE TITLE
Draconic metals aren't available

### ISSUE THREAD

**Issue by George0079** [Bartz24/MoarTinkers#34]
For some reason, I can't craft the draconic stuff. I have the up-to-date versions of this mod and draconic evolution, but I can't craft the draconic stuff, nor can I see them in NEI.

**Comment by ToMe25** [comment]
I am having the same Issue using:
Forge 1.12.2-14.23.4.2703,
RedstoneFlux 1.12-2.0.2.3,
BrandonsCore 1.12-2.4.2.157-universal,
Draconic Evolution 1.12-2.3.11.290-universal,
Mantle 1.12-1.3.2.24,
Tinker's Construct 1.12.2-2.10.1.87,
MoarTinkers 0.5.4,
Just Enough Items 1.12.2-4.9.1.188

All Draconic Evolution Material are enabled in the Config File but not Existant in-game!

**Comment by Bartz24** [comment]
Fixed in 0.6.0

**Comment by ToMe25** [comment]
Thanks :)
