### ISSUE TITLE
Issue with MoarTinkers: unknown problem causing crash

### ISSUE THREAD

**Issue by markismodded** [Bartz24/MoarTinkers#36]
A detailed walkthrough of the error, its code path and all known details is as follows: 
-- System Details --
 Details: 	
Minecraft Version: 1.12.2 	
Operating System: Windows 10 (amd64) version 10.0 	
Java Version: 1.8.0_25, Oracle Corporation 	
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation 	
Memory: 1111774032 bytes (1060 MB) / 2225078272 bytes (2122 MB) up to 4534042624 bytes (4324 MB) 	
JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4864m -Xms256m -XX:PermSize=256m 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 	FML: MCP 9.42 
Powered by Forge 14.23.4.2705 
90 mods loaded, 90 mods active 	
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored  	
 UCH   \| minecraft                         \| 1.12.2                 \| minecraft.jar                                    \| None                                     UCH   \| mcp                               \| 9.42                   \| minecraft.jar                                    \| None                                     UCH   \| FML                               \| 8.0.99.99              \| forge-1.12.2-14.23.4.2705.jar                    \| e3c3d50c7c986df74c645c0ac54639741c90a557
UCH   \| forge                             \| 14.23.4.2705           \| forge-1.12.2-14.23.4.2705.jar                    \| e3c3d50c7c986df74c645c0ac54639741c90a557 
UCH   \| advancedrocketrycore              \| 1                      \| minecraft.jar                                    \| None                                     UCH   \| openmodscore                      \| 0.11.5                 \| minecraft.jar                                    \| None                                     UCH   \| srm-hooks                         \| 1.12.2-1.0.0           \| minecraft.jar                                    \| None                                   UCH   \| actuallyadditions                 \| 1.12.2-r135            \| ActuallyAdditions-1.12.2-r135.jar                \| None                                     
UCH   \| redstoneflux                      \| 2.0.2                  \| RedstoneFlux-1.12-2.0.2.3-universal.jar          \| 8a6abf2cb9e141b866580d369ba6548732eff25f
UCH   \| cofhcore                          \| 4.5.1                  \| CoFHCore-1.12.2-4.5.1.18-universal.jar           \| None                                    
UCH   \| libvulpes                         \| 0.2.8.-31              \| LibVulpes-1.12.2-0.2.8-31-universal.jar          \| None                                    
UCH   \| advancedrocketry                  \| 1.4.0.-33              \| AdvancedRocketry-1.12.2-1.4.0-33.jar             \| None                                   
UCH   \| appliedenergistics2               \| rv5-stable-11          \| appliedenergistics2-rv5-stable-11.jar            \| None                                    
UCH   \| bdlib                             \| 1.14.3.12              \| bdlib-1.14.3.12-mc1.12.2.jar                     \| None                                     UCH   \| ae2stuff                          \| 0.7.0.4                \| ae2stuff-0.7.0.4-mc1.12.2.jar                    \| None                                     UCH   \| applecore                         \| 3.1.1                  \| AppleCore-mc1.12.2-3.1.1.jar                     \| None                                     UCH   \| jei                               \| 4.9.1.188              \| jei_1.12.2-4.9.1.188.jar                         \| None                                     UCH   \| appleskin                         \| 1.0.9                  \| AppleSkin-mc1.12-1.0.9.jar                       \| None                                     UCH   \| baubles                           \| 1.5.2                  \| Baubles-1.12-1.5.2.jar                           \| None                                     UCH   \| astralsorcery                     \| 1.8.10                 \| astralsorcery-1.12.2-1.8.10.jar                  \| a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 
UCH   \| bedrockbgone                      \| 5.0.8                  \| BedrockBGone-1.12.2-5.0-b8.jar                   \| None                                  
UCH   \| betterbuilderswands               \| 0.11.1                 \| BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar  \| None                                    
UCH   \| codechickenlib                    \| 3.1.8.341              \| CodeChickenLib-1.12.2-3.1.8.341-universal.jar    \| f1850c39b2516232a2108a7bd84d1cb5df93b261 
UCH   \| brandonscore                      \| 2.4.2                  \| BrandonsCore-1.12-2.4.2.157-universal.jar        \| None                                     
UCH   \| buildcraftlib                     \| 7.99.17                \| buildcraft-7.99.17.jar                           \| None                                     UCH   \| buildcraftcore                    \| 7.99.17                \| buildcraft-7.99.17.jar                           \| None                                     UCH   \| buildcraftbuilders                \| 7.99.17                \| buildcraft-7.99.17.jar                           \| None                                     UCH   \| buildcraftenergy                  \| 7.99.17                \| buildcraft-7.99.17.jar                           \| None                                     UCH   \| buildcraftfactory                 \| 7.99.17                \| buildcraft-7.99.17.jar                           \| None                                     UCH   \| buildcraftrobotics                \| 7.99.17                \| buildcraft-7.99.17.jar                           \| None                                     UCH   \| buildcrafttransport               \| 7.99.17                \| buildcraft-7.99.17.jar                           \| None                                     UCH   \| buildcraftsilicon                 \| 7.99.17                \| buildcraft-7.99.17.jar                           \| None                                     UCH   \| rf-capability-adapter             \| 1.0                    \| capabilityadapter-1.0.jar                        \| None                                     UCH   \| chancecubes                       \| 1.12.2-3.1.0.217       \| ChanceCubes-1.12.2-3.1.0.217.jar                 \| None                                     
UCH   \| ctm                               \| MC1.12-0.2.3.12        \| CTM-MC1.12-0.2.3.12.jar                          \| None                                    
UCH   \| chisel                            \| MC1.12.2-0.2.0.31      \| Chisel-MC1.12.2-0.2.0.31.jar                     \| None                                     
UCH   \| cofhworld                         \| 1.2.0                  \| CoFHWorld-1.12.2-1.2.0.5-universal.jar           \| 8a6abf2cb9e141b866580d369ba6548732eff25f
UCH   \| cucumber                          \| 1.1.0                  \| cucumber-1.12-1.1.0.jar                          \| None                                     UCH   \| dimdoors                          \| 3.0.9+287              \| DimensionalDoors-3.0.9-287.jar                   \| None                                   
UCH   \| thermalfoundation                 \| 2.5.0                  \| ThermalFoundation-1.12.2-2.5.0.19-universal.jar  \| 8a6abf2cb9e141b866580d369ba6548732eff25f
UCH   \| draconicevolution                 \| 2.3.11                 \| Draconic-Evolution-1.12-2.3.11.290-universal.jar \| None                                     
UCH   \| endercore                         \| 1.12.2-0.5.30          \| EnderCore-1.12.2-0.5.30.jar                      \| None                                     
UCH   \| thermalexpansion                  \| 5.5.0                  \| ThermalExpansion-1.12.2-5.5.0.29-universal.jar   \| 8a6abf2cb9e141b866580d369ba6548732eff25f
UCH   \| enderio                           \| 5.0.25                 \| EnderIO-1.12.2-5.0.25.jar                        \| None                                     UCH   \| enderiointegrationtic             \| 5.0.25                 \| EnderIO-1.12.2-5.0.25.jar                        \| None                                     
UCH   \| enderiobase                       \| 5.0.25                 \| EnderIO-1.12.2-5.0.25.jar                        \| None                                     UCH   \| enderioconduits                   \| 5.0.25                 \| EnderIO-1.12.2-5.0.25.jar                        \| None                                     
UCH   \| enderioconduitsappliedenergistics \| 5.0.25                 \| EnderIO-1.12.2-5.0.25.jar                        \| None                                 
UCH   \| enderioconduitsopencomputers      \| 5.0.25                 \| EnderIO-1.12.2-5.0.25.jar                        \| None                                
UCH   \| enderioconduitsrefinedstorage     \| 5.0.25                 \| EnderIO-1.12.2-5.0.25.jar                        \| None                                    
UCH   \| enderiointegrationforestry        \| 5.0.25                 \| EnderIO-1.12.2-5.0.25.jar                        \| None                                    
UCH   \| mantle                            \| 1.12-1.3.2.24          \| Mantle-1.12-1.3.2.24.jar                         \| None                                     UCH   \| tconstruct                        \| 1.12.2-2.10.0.81       \| TConstruct-1.12.2-2.10.0.81.jar                  \| None                                     
UCH   \| enderiointegrationticlate         \| 5.0.25                 \| EnderIO-1.12.2-5.0.25.jar                        \| None                                 
UCH   \| enderiomachines                   \| 5.0.25                 \| EnderIO-1.12.2-5.0.25.jar                        \| None                                
UCH   \| enderiopowertools                 \| 5.0.25                 \| EnderIO-1.12.2-5.0.25.jar                        \| None                                   
UCH   \| enderstorage                      \| 2.4.3.130              \| EnderStorage-1.12.2-2.4.3.130-universal.jar      \| f1850c39b2516232a2108a7bd84d1cb5df93b261
UCH   \| exnihilocreatio                   \| 1.12-0.2.2             \| exnihilocreatio-1.12-0.2.2.jar                   \| None                                     UCH   \| excompressum                      \| 3.0.20                 \| ExCompressum_1.12.2-3.0.20.jar                   \| None                                 
UCH   \| extrautils2                       \| 1.0                    \| extrautils2-1.12-1.7.6.jar                       \| None                                     UCH   \| zerocore                          \| 1.12-0.1.2.1           \| zerocore-1.12-0.1.2.1.jar                        \| None                                     UCH   \| bigreactors                       \| 1.12.2-0.4.5.48        \| ExtremeReactors-1.12.2-0.4.5.48.jar              \| None                                  
UCH   \| fastleafdecay                     \| v14                    \| FastLeafDecay-v14.jar                            \| None                                     UCH   \| gravestone                        \| 1.10.1                 \| gravestone-1.10.1.jar                            \| None                                     UCH   \| ichunutil                         \| 7.1.4                  \| iChunUtil-1.12.2-7.1.4.jar                       \| None                                     UCH   \| ic2                               \| 2.8.73-ex112           \| industrialcraft-2-2.8.73-ex112.jar               \| de041f9f6187debbc77034a344134053277aa3b0
UCH   \| ironchest                         \| 1.12.2-7.0.40.824      \| ironchest-1.12.2-7.0.40.824.jar                  \| None                                     
UCH   \| journeymap                        \| 1.12.2-5.5.2           \| journeymap-1.12.2-5.5.2.jar                      \| None                                  
UCH   \| lootbags                          \| 2.5.6                  \| LootBags-1.12.2-2.5.6.jar                        \| None                                     UCEE  \| moartinkers                       \| 0.5.4                  \| moartinkers-0.5.4.jar                            \| None                                     UC    \| mysticalagriculture               \| 1.6.10                 \| mysticalagriculture-1.12-1.6.10.jar              \| None                                     
UC    \| mysticalagradditions              \| 1.2.8                  \| mysticalagradditions-1.12-1.2.8.jar              \| None                                   
UC    \| openmods                          \| 0.11.5                 \| OpenModsLib-1.12.2-0.11.5.jar                    \| d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5
UC    \| openblocks                        \| 1.7.6                  \| OpenBlocks-1.12.2-1.7.6.jar                      \| d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5
UC    \| harvestcraft                      \| 1.12.2u                \| Pam's HarvestCraft 1.12.2u.jar                   \| None                                     
UC    \| redstonearsenal                   \| 2.5.0                  \| RedstoneArsenal-1.12.2-2.5.0.10-universal.jar    \| 8a6abf2cb9e141b866580d369ba6548732eff25f
UC    \| secretroomsmod                    \| 5.6.4                  \| secretroomsmod-1.12.2-5.6.4.jar                  \| None                                    
UC    \| snad                              \| 1.12.1-1.7.09.16a      \| Snad-1.12.1-1.7.09.16a.jar                       \| None                                     
UC    \| sync                              \| 7.0.2                  \| Sync-1.12.2-7.0.2.jar                            \| None                                     UC    \| thermalcultivation                \| 0.3.0                  \| ThermalCultivation-1.12.2-0.3.0.7-universal.jar  \| 8a6abf2cb9e141b866580d369ba6548732eff25f 
UC    \| thermaldynamics                   \| 2.5.1                  \| ThermalDynamics-1.12.2-2.5.1.13-universal.jar    \| 8a6abf2cb9e141b866580d369ba6548732eff25f 
UC    \| tinkersaddons                     \| 1.0.7                  \| Tinkers' Addons-1.12.1-1.0.7.jar                 \| None                                     
UC    \| tinkersjei                        \| 1.0                    \| tinkersjei-1.0.jar                               \| None                                     UC    \| tinkertoolleveling                \| 1.12-1.0.4.DEV.5d716b9 \| TinkerToolLeveling-1.12-1.0.4.jar                \| None                                     
UC    \| tp                                \| 3.2.28                 \| tinyprogressions-1.12.2-3.3.28-Release.jar       \| None                                     UC    \| veinminer                         \| 0.38.1                 \| VeinMiner-1.12-0.38.1.639+134fb1e.jar            \| None                                     
UC    \| veinminermodsupport               \| 0.38.1                 \| VeinMiner-1.12-0.38.1.639+134fb1e.jar            \| None                                   
UC    \| wanionlib                         \| 1.12.2-1.5             \| WanionLib-1.12.2-1.5.jar                         \| None                                     UC    \| wawla                             \| 2.5.253                \| Wawla-1.12.2-2.5.253.jar                         \| d476d1b22b218a10d845928d1665d45fce301b27
UC    \| unidict                           \| 1.12.2-2.5c            \| UniDict-1.12.2-2.5c.jar                          \| None                                     \|  	Loaded coremods (and transformers):  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)   team.chisel.ctm.client.asm.CTMTransformer AstralCore (astralsorcery-1.12.2-1.8.10.jar)    SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)   com.wynprice.secretroomsmod.core.SecretRoomsTransformer OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)   openmods.core.OpenModsClassTransformer AppleCore (AppleCore-mc1.12.2-3.1.1.jar)   squeek.applecore.asm.TransformerModuleHandler AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-33.jar)   zmaster587.advancedRocketry.asm.ClassTransformer EnderCorePlugin (EnderCore-1.12.2-0.5.30.jar)   com.enderio.core.common.transform.EnderCoreTransformer   com.enderio.core.common.transform.SimpleMixinPatcher 	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4425' Renderer: 'Intel(R) HD Graphics 4000' 	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED] 	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554 	Pulsar/tconstruct loaded Pulses:  		- TinkerCommons (Enabled/Forced) 		- TinkerWorld (Enabled/Not Forced) 		- TinkerTools (Enabled/Not Forced) 		- TinkerHarvestTools (Enabled/Forced) 		- TinkerMeleeWeapons (Enabled/Forced) 		- TinkerRangedWeapons (Enabled/Forced) 		- TinkerModifiers (Enabled/Forced) 		- TinkerSmeltery (Enabled/Not Forced) 		- TinkerGadgets (Enabled/Not Forced) 		- TinkerOredict (Enabled/Forced) 		- TinkerIntegration (Enabled/Forced) 		- TinkerFluids (Enabled/Forced) 		- TinkerMaterials (Enabled/Forced) 		- TinkerModelRegister (Enabled/Forced) 		- chiselIntegration (Enabled/Not Forced)  	List of loaded APIs:  		* actuallyadditionsapi (33) from ActuallyAdditions-1.12.2-r135.jar 		* AppleCoreAPI (3.1.0) from AppleCore-mc1.12.2-3.1.1.jar 		* appliedenergistics2\|API (rv5) from appliedenergistics2-rv5-stable-11.jar 		* Baubles\|API (1.4.0.2) from Baubles-1.12-1.5.2.jar 		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar 		* bigreactors\|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.48.jar 		* BuildCraftAPI\|blocks (1.0) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|boards (2.0) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|core (2.2) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|crops (1.1) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|enums (1.0) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|events (2.0) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|facades (1.1) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|filler (5.0) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|fuels (2.0) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|gates (4.1) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|items (1.1) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|library (2.0) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|lists (1.0) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|power (1.3) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|recipes (3.0) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|robotics (3.0) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|statements (1.1) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|tiles (1.2) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|tools (1.0) from buildcraft-7.99.17.jar 		* BuildCraftAPI\|transport (5.0) from buildcraft-7.99.17.jar 		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar 		* ChiselAPI\|Carving (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar 		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.5.1.18-universal.jar 		* ctm-api (0.1.0) from CTM-MC1.12-0.2.3.12.jar 		* ctm-api-events (0.1.0) from CTM-MC1.12-0.2.3.12.jar 		* ctm-api-models (0.1.0) from CTM-MC1.12-0.2.3.12.jar 		* ctm-api-textures (0.1.0) from CTM-MC1.12-0.2.3.12.jar 		* ctm-api-utils (0.1.0) from CTM-MC1.12-0.2.3.12.jar 		* DraconicEvolution\|API (1.3) from Draconic-Evolution-1.12-2.3.11.290-universal.jar 		* enderioapi (4.0.0) from EnderIO-1.12.2-5.0.25.jar 		* enderioapi\|addon (4.0.0) from EnderIO-1.12.2-5.0.25.jar 		* enderioapi\|capacitor (4.0.0) from EnderIO-1.12.2-5.0.25.jar 		* enderioapi\|conduits (4.0.0) from EnderIO-1.12.2-5.0.25.jar 		* enderioapi\|farm (4.0.0) from EnderIO-1.12.2-5.0.25.jar 		* enderioapi\|redstone (4.0.0) from EnderIO-1.12.2-5.0.25.jar 		* enderioapi\|teleport (4.0.0) from EnderIO-1.12.2-5.0.25.jar 		* enderioapi\|tools (4.0.0) from EnderIO-1.12.2-5.0.25.jar 		* enderioapi\|upgrades (4.0.0) from EnderIO-1.12.2-5.0.25.jar 		* ExCompressum\|API (1.0) from ExCompressum_1.12.2-3.0.20.jar 		* iChunUtil API (1.2.0) from iChunUtil-1.12.2-7.1.4.jar 		* journeymap\|client-api (1.4) from journeymap-1.12.2-5.5.2.jar 		* journeymap\|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar 		* journeymap\|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar 		* journeymap\|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar 		* journeymap\|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar 		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.9.1.188.jar 		* openblocks\|api (1.2) from OpenBlocks-1.12.2-1.7.6.jar 		* veinminerApi (0.3) from VeinMiner-1.12-0.38.1.639+134fb1e.jar 		* zerocore\|API\|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar 		* zerocore\|API\|multiblock\|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar 		* zerocore\|API\|multiblock\|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar 		* zerocore\|API\|multiblock\|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar
--
16:37:01 | STDOUT | main | info | [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\---------------\Documents\Curse\Minecraft\Instances\something different\crash-reports\crash-2018-05-30_16.37.01-client.txt

Configuration settings for moartinkers:
    B:"Add Melting for red/glowstone and ender pearls"=true
    B:"Allow Advanced Alloy Material"=true
    B:"Allow Alabaster Material"=true
    B:"Allow Aluminum Material"=true
    B:"Allow Awakened Draconium Material"=true
    B:"Allow Basalt Material"=true
    B:"Allow Blutonium Material"=true
    B:"Allow Brass Material"=true
    B:"Allow Certus Quartz Material"=true
    B:"Allow Chaotic Draconium Material"=true
    B:"Allow Chrome Material"=true
    B:"Allow Conductive Iron Material"=false
    B:"Allow Constantan Material"=true
    B:"Allow Cyanite Material"=true
    B:"Allow Dark Matter Material"=true
    B:"Allow Dark Steel Material"=false
    B:"Allow Draconium Material"=true
_______________________________________________________________________________________________________________
issue is: what is causing minecraft to crash?

**Comment by YaibaToKen** [comment]
is that the full crashlog? Also, please use a service like gist or pastebin for log files from now on as that makes reading the issue that much easier

**Comment by markismodded** [comment]
@YaibaToKen no, it is not complete. i would provide it, but recently, Extra Utilities 2 has been having fatal errors. i will do my best.

**Comment by markismodded** [comment]
@YaibaToKen https://pastebin.com/C1RsQW25

**Comment by YaibaToKen** [comment]
On line 502, ` [TCon API] Could not register Material "soularium"` that's what you're looking for. Disable that material in Moar Tinker's config file. If it crashes again, look for a similar entry in the new crashlog. Disable that material as well. Do that till Moar Tinkers stops crashing.

**Comment by markismodded** [comment]
@YaibaToKen , I appologize for the frequent mentions, but i must thank you on your help. it seems as though the problem has been fixed, a new problem arises from what i feel is partially responsible by this mod. if so, i implore you to help. if not, please push me in the correct direction where i can receive help:

https://pastebin.com/5EkQWbQY

**Comment by YaibaToKen** [comment]
Moar Tinkers is no longer crashing but something is making Minecraft's internal code crash.. Unfortunately I couldn't tell what mod is causing this, but I ask that you make sure all of your mods are updated. Also, disable Moar Tinkers and check if the crash still occurs.

**Comment by markismodded** [comment]
@YaibaToKen 
Line 1098 and 1099 are specifically stated as fatal errors in the output log. I assume that is the main problem? ( these specifically state tconstruct (which moartinkers is an addon to) and EU2, which Im not sure whats been happening to, but its recently been getting fatal errors too

https://pastebin.com/ND1UmbT1 
this is where I tested without MoarTinkers, and the Fatal Error did not show up for it. the fatal error for EU2, on the other hand, did, but at this point it is expected.

**Comment by YaibaToKen** [comment]
could I ask you to test without EU2 as well? Other than that, start with just tinker's and it's addons and slowly add the mods back. A soon as it crashes check to see which of the last added mods could have caused it.

**Comment by markismodded** [comment]
I have tried turning EU2 off with and without MoarTinkers, and both crashed for seemingly different reasons (the time both were off im not sure what made it crash: https://pastebin.com/WgwGfeQz)

**Comment by YaibaToKen** [comment]
A mod is messing model loading, not really familiar with how Secret Rooms works, but it might be the culprit. Mind testing without it? Though I do seriously advise you to start from a small amount of mods that seem to work and slowly add the remaining ones till it crashes. The last mod added is usually the culprit.

**Comment by markismodded** [comment]
secret rooms is not the culprit. i used both secret rooms and EU2 before adding moartinkers, tinkers addons, and iron chests. ( I have tested without tinkers addons and it fixed nothing) I think i should note that i updated Thermal Foundation, Cofh core, and other thermal and COFH addons and EU2 stopped working. i think MoarTinkers is part of the problem, but not entirely the problem.

**Comment by YaibaToKen** [comment]
I'm sorry that I can't help further :/

**Comment by Bartz24** [comment]
I took a look too. Sorry, I don't know either. I'm going to close this issue,
