### ISSUE TITLE
Manasteel Arrows don't seem to use mana instead of ammo

### ISSUE THREAD

**Issue by erindalc** [Bartz24/MoarTinkers#38]
Moar Tinkers version: 0.5.4
Tinker's Version: 2.10.1.87

With a Band of Mana equipped (yes it has some mana stored), Manasteel arrows consume ammo when fired.

I'm not sure if it's also consuming mana, but given how much I've been shooting my bow without a lot of drain I don't think so.

Gfycat demo: https://giant.gfycat.com/FixedPleasedCottontail.webm

**Comment by erindalc** [comment]
Perhaps similar to #33 because I don't think my manasteel tools are working at all.

**Comment by YaibaToKen** [comment]
AFAIK the code for the manasteel material to use mana to repair itself isn't working, not sure if the logic is fully implemented or not.

**Comment by Bartz24** [comment]
Yeah. The repair traits don't seem to be working correctly on any tools right now

**Comment by Bartz24** [comment]
Fixed in 0.6.0

But arrows will not be "repaired" with mana
