### ISSUE TITLE
More Materials sugestions

### ISSUE THREAD

**Issue by vrork** [Bartz24/MoarTinkers#4]
I noticed some missing materials and i have some sugestions of materials you could add:
Living wood from Botania
TNT and Alumite

**Comment by Landmaster** [comment]
Hey, those last two are from my mod, PlusTiC! ;)

**Comment by vrork** [comment]
Indeed they are. But i dont know if your mod and his are compatible. And his mod have more things at the moment

**Comment by Bartz24** [comment]
TNT is a no...just no. too 'splody
Alumite...idk, is it really needed? Sharpening kits are a thing
Livingwood/rock I'll add to my list

**Comment by vrork** [comment]
TNT is fun. You can be very creativy with it. Its not needed but the more options we have the better.

Btw Bartz, do you know the mod Tinkers Defense? If no, its basically a mod that add tinkers shields and that is something we reaaaly need. Any chance of you doing your version? (The dev seems to have abandoned it and is quite a ***** when we ask him to update)

**Comment by Bartz24** [comment]
The battlesign in TiC 1.10 acts as a shield now :D

**Comment by vrork** [comment]
Its not a shield. I would really like proper shields, not battle signs. I would love other types of weapons too (spears, hammers, katanas, and soo on), but that i can live without the new weapons
