### ISSUE TITLE
[1.12.2] [Request] Adding more config option to the .cfg file

### ISSUE THREAD

**Issue by Draskh** [Bartz24/MoarTinkers#41]
If I add Moar Tinkers to my pack a new melting recipe for redstone appears which temperature is too high. There is no config option to turn this off and I did not find anything about redstone in the source code , but it only appears if Moar Tinkers is present.
![2018-09-25_13 35 15](https://user-images.githubusercontent.com/26455012/46012064-3d587680-c0c8-11e8-8376-d28822ba8171.png)

**Comment by Bartz24** [comment]
Moar Tinkers by default allows blazing pyrotheum to be used to heat it up. which has a much higher max temperature

**Comment by Draskh** [comment]
But could you implement a config to turn redstone, glowstone and enderpearl integration off? This has been added by other mods already as the pyrotheum integration and Moar Tinkers overwrites them.

**Comment by Draskh** [comment]
I changed a title to make a request though.
