### ISSUE TITLE
Too OP trait

### ISSUE THREAD

**Issue by MasterFee** [Bartz24/MoarTinkers#6]
The 'Too OP' trait gives any DE material 0 modifiers but if I have [Tinkers' Tool Leveling](https://minecraft.curseforge.com/projects/tinkers-tool-leveling) installed I'm still able to get modifier through leveling. I don't know if you want a player to start with no modifiers and gather them then by leveling (if Tinkers' Tool Leveling is installed) or if their tools should never be modifiable.
By the way I really love your mod it literally feels like a balanced version of ExtraTIC <3.

**Comment by Bartz24** [comment]
This is fine
