### ISSUE TITLE
Moar tinkers dosn't work with latest 1.10.2 tinkers.

### ISSUE THREAD

**Issue by Claycorp** [Bartz24/MoarTinkers#7]
https://pastebin.com/Er5dxZ7q

**Comment by TartaricAcid** [comment]
Have the same error.

**Comment by Claycorp** [comment]
I switched to PlusTic as this hasn't been updated in a while. Its fairly similar and was updated to the latest tinkers if you are interested.

**Comment by Bartz24** [comment]
It'll be updated today :D

**Comment by Bartz24** [comment]
Fixed in next version
