### ISSUE TITLE
No Way to Get Destabilized Redstone(molten) In Smeltery

### ISSUE THREAD

**Issue by kenijey** [Bartz24/MoarTinkers#9]
when i click that red thing (destabilized redstone) in picture, there is no alloying recipe for that.
![242](https://user-images.githubusercontent.com/24831406/29072305-bc577a4e-7c4f-11e7-9cc8-6caa1650abec.PNG)
u added support for it but u forgot to add Destabilized Clathrate to smelt in smeltery :) u should add that and redstone block/redstone to get destabilized redstone in smeltery. hope u do it soon.. thank you..
MC 1.12 forge 2443

**Comment by Bartz24** [comment]
added redstone, glowstone, and ender pearl melting to next version

**Comment by kenijey** [comment]
thanks a lot, waiting eagerly.
